// <auto-generated />
using System;
using HRM.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRM.Migrations
{
    [DbContext(typeof(HrmContext))]
    partial class HrmContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HRM.Models.ActivityLog", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Action")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<DateTime?>("CreatedDate")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                b.Property<string>("Description")
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<int>("EntityId")
                    .HasColumnType("int");

                b.Property<string>("EntityName")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<int>("UserId")
                    .HasColumnType("int");

                b.HasKey("Id")
                    .HasName("PK__Activity__3214EC07F1A3E283");

                b.HasIndex("UserId");

                b.ToTable("ActivityLogs");
            });

            modelBuilder.Entity("HRM.Models.Attendance", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<DateTime>("CheckInTime")
                    .HasColumnType("datetime");

                b.Property<DateTime?>("CheckOutTime")
                    .HasColumnType("datetime");

                b.Property<int>("EmployeeId")
                    .HasColumnType("int");

                b.Property<string>("Status")
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.Property<decimal?>("WorkingHours")
                    .HasColumnType("decimal(5, 2)");

                b.HasKey("Id")
                    .HasName("PK__Attendan__3214EC0763B8F39C");

                b.HasIndex("EmployeeId");

                b.ToTable("Attendance", (string)null);
            });

            modelBuilder.Entity("HRM.Models.Department", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<DateTime?>("CreatedDate")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                b.Property<string>("Description")
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<int?>("ManagerId")
                    .HasColumnType("int");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.HasKey("Id")
                    .HasName("PK__Departme__3214EC07B82FEBF2");

                b.ToTable("Departments");
            });

            modelBuilder.Entity("HRM.Models.Employee", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Address")
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<decimal>("BasicSalary")
                    .HasColumnType("decimal(18, 2)");

                b.Property<DateTime?>("CreatedDate")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                b.Property<DateOnly>("DateOfBirth")
                    .HasColumnType("date");

                b.Property<int?>("DepartmentId")
                    .HasColumnType("int");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("FirstName")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("FullName")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("Gender")
                    .HasColumnType("int");

                b.Property<DateOnly>("HireDate")
                    .HasColumnType("date");

                b.Property<string>("LastName")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<DateTime?>("ModifiedDate")
                    .HasColumnType("datetime");

                b.Property<string>("Phone")
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.Property<string>("PhotoPath")
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.Property<int>("UserId")
                    .HasColumnType("int");

                b.HasKey("Id")
                    .HasName("PK__Employee__3214EC07F3E17BB3");

                b.HasIndex("DepartmentId");

                b.HasIndex("UserId");

                b.HasIndex(new[] { "Email" }, "UQ__Employee__A9D10534D9F8FBF8")
                    .IsUnique();

                b.ToTable("Employees");
            });

            modelBuilder.Entity("HRM.Models.Leave", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<DateTime?>("ApprovalDate")
                    .HasColumnType("datetime");

                b.Property<int?>("ApprovedBy")
                    .HasColumnType("int");

                b.Property<int>("EmployeeId")
                    .HasColumnType("int");

                b.Property<DateOnly>("EndDate")
                    .HasColumnType("date");

                b.Property<string>("LeaveType")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("Reason")
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<DateOnly>("StartDate")
                    .HasColumnType("date");

                b.Property<string>("Status")
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.HasKey("Id")
                    .HasName("PK__Leaves__3214EC078A1E8ECA");

                b.HasIndex("ApprovedBy");

                b.HasIndex("EmployeeId");

                b.ToTable("Leaves");
            });

            modelBuilder.Entity("HRM.Models.Notification", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<DateTime?>("CreatedDate")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                b.Property<int?>("DepartmentId")
                    .HasColumnType("int");

                b.Property<bool?>("IsRead")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bit")
                    .HasDefaultValue(false);

                b.Property<string>("Message")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int?>("ReceiverUserId")
                    .HasColumnType("int");

                b.Property<int>("SenderUserId")
                    .HasColumnType("int");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.HasKey("Id")
                    .HasName("PK__Notifica__3214EC0757A9EF61");

                b.HasIndex("DepartmentId");

                b.HasIndex("ReceiverUserId");

                b.HasIndex("SenderUserId");

                b.ToTable("Notifications");
            });

            modelBuilder.Entity("HRM.Models.Salary", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<decimal?>("Allowance")
                    .HasColumnType("decimal(18, 2)");

                b.Property<decimal>("BaseSalary")
                    .HasColumnType("decimal(18, 2)");

                b.Property<decimal?>("Bonus")
                    .HasColumnType("decimal(18, 2)");

                b.Property<decimal?>("Deduction")
                    .HasColumnType("decimal(18, 2)");

                b.Property<int>("EmployeeId")
                    .HasColumnType("int");

                b.Property<int>("Month")
                    .HasColumnType("int");

                b.Property<DateTime?>("PaymentDate")
                    .HasColumnType("datetime");

                b.Property<string>("Status")
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.Property<int>("Year")
                    .HasColumnType("int");

                b.HasKey("Id")
                    .HasName("PK__Salaries__3214EC07FC2CD556");

                b.HasIndex("EmployeeId");

                b.ToTable("Salaries");
            });

            modelBuilder.Entity("HRM.Models.User", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<DateTime?>("CreatedDate")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                b.Property<DateTime?>("LastLoginDate")
                    .HasColumnType("datetime");

                b.Property<string>("Password")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Role")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.Property<string>("Username")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.HasKey("Id")
                    .HasName("PK__Users__3214EC07E25E1225");

                b.HasIndex(new[] { "Username" }, "UQ__Users__536C85E4663AEF39")
                    .IsUnique();

                b.ToTable("Users");
            });

            modelBuilder.Entity("HRM.Models.ActivityLog", b =>
            {
                b.HasOne("HRM.Models.User", "User")
                    .WithMany("ActivityLogs")
                    .HasForeignKey("UserId")
                    .IsRequired()
                    .HasConstraintName("FK__ActivityL__UserI__59FA5E80");

                b.Navigation("User");
            });

            modelBuilder.Entity("HRM.Models.Attendance", b =>
            {
                b.HasOne("HRM.Models.Employee", "Employee")
                    .WithMany("Attendances")
                    .HasForeignKey("EmployeeId")
                    .IsRequired()
                    .HasConstraintName("FK__Attendanc__Emplo__4BAC3F29");

                b.Navigation("Employee");
            });

            modelBuilder.Entity("HRM.Models.Employee", b =>
            {
                b.HasOne("HRM.Models.Department", "Department")
                    .WithMany("Employees")
                    .HasForeignKey("DepartmentId")
                    .HasConstraintName("FK__Employees__Depar__45F365D3");

                b.HasOne("HRM.Models.User", "User")
                    .WithMany("Employees")
                    .HasForeignKey("UserId")
                    .IsRequired()
                    .HasConstraintName("FK__Employees__UserI__44FF419A");

                b.Navigation("Department");

                b.Navigation("User");
            });

            modelBuilder.Entity("HRM.Models.Leave", b =>
            {
                b.HasOne("HRM.Models.Employee", "ApprovedByNavigation")
                    .WithMany("LeafApprovedByNavigations")
                    .HasForeignKey("ApprovedBy")
                    .HasConstraintName("FK__Leaves__Approved__4F7CD00D");

                b.HasOne("HRM.Models.Employee", "Employee")
                    .WithMany("LeafEmployees")
                    .HasForeignKey("EmployeeId")
                    .IsRequired()
                    .HasConstraintName("FK__Leaves__Employee__4E88ABD4");

                b.Navigation("ApprovedByNavigation");

                b.Navigation("Employee");
            });

            modelBuilder.Entity("HRM.Models.Notification", b =>
            {
                b.HasOne("HRM.Models.Department", "Department")
                    .WithMany("Notifications")
                    .HasForeignKey("DepartmentId")
                    .HasConstraintName("FK__Notificat__Depar__5629CD9C");

                b.HasOne("HRM.Models.User", "ReceiverUser")
                    .WithMany("NotificationReceiverUsers")
                    .HasForeignKey("ReceiverUserId")
                    .HasConstraintName("FK__Notificat__Recei__5535A963");

                b.HasOne("HRM.Models.User", "SenderUser")
                    .WithMany("NotificationSenderUsers")
                    .HasForeignKey("SenderUserId")
                    .IsRequired()
                    .HasConstraintName("FK__Notificat__Sende__5441852A");

                b.Navigation("Department");

                b.Navigation("ReceiverUser");

                b.Navigation("SenderUser");
            });

            modelBuilder.Entity("HRM.Models.Salary", b =>
            {
                b.HasOne("HRM.Models.Employee", "Employee")
                    .WithMany("Salaries")
                    .HasForeignKey("EmployeeId")
                    .IsRequired()
                    .HasConstraintName("FK__Salaries__Employ__48CFD27E");

                b.Navigation("Employee");
            });

            modelBuilder.Entity("HRM.Models.Department", b =>
            {
                b.Navigation("Employees");

                b.Navigation("Notifications");
            });

            modelBuilder.Entity("HRM.Models.Employee", b =>
            {
                b.Navigation("Attendances");

                b.Navigation("LeafApprovedByNavigations");

                b.Navigation("LeafEmployees");

                b.Navigation("Salaries");
            });

            modelBuilder.Entity("HRM.Models.User", b =>
            {
                b.Navigation("ActivityLogs");

                b.Navigation("Employees");

                b.Navigation("NotificationReceiverUsers");

                b.Navigation("NotificationSenderUsers");
            });
#pragma warning restore 612, 618
        }
    }
}
